spring:
  application:
    name: zuul-service
server:
  port: 9501
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
zuul:
  routes:
    ribbon:
      path: /api-ribbon/**
      serviceId: ribbon-server
    feign:
      path: /api-feign/**
      serviceId: feign-service
